# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  entity.service:
    class: AppBundle\Services\EntityService
    arguments: ["@doctrine.orm.entity_manager"]