# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  model.service:
    class: AppBundle\Model\MethodModel
    arguments: ["@service_container"]